# Generated by Django 4.0.7 on 2024-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(default=11233, max_length=11, unique=True, verbose_name='phone_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
