# Generated by Django 4.0.7 on 2024-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_phone_number_alter_baseuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='phone_number'),
        ),
    ]
